# Generated by Django 6.0 on 2025-12-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Castle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Назва замку")),
                (
                    "description",
                    models.TextField(verbose_name="Історична довідка / Опис"),
                ),
                (
                    "model_file",
                    models.FileField(
                        upload_to="3d_models/", verbose_name="Файл 3D моделі (.glb)"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="castle_covers/", verbose_name="Обкладинка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Замок",
                "verbose_name_plural": "Замки",
            },
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ПІБ")),
                ("bio", models.TextField(verbose_name="Біографія")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="researcher/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("number", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Дослідник",
                "verbose_name_plural": "Дослідники",
            },
        ),
        migrations.CreateModel(
            name="ResearchWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Назва роботи"),
                ),
                ("summary", models.TextField(verbose_name="Короткий опис (анотація)")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="Файл роботи (PDF)",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Посилання на публікацію"
                    ),
                ),
                ("publish_date", models.DateField(verbose_name="Дата публікації")),
            ],
            options={
                "verbose_name": "Наукова робота",
                "verbose_name_plural": "Наукові роботи",
            },
        ),
    ]
