# Generated by Django 6.0 on 2025-12-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researcher",
            name="bio_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="researcher/",
                verbose_name="Фото для біографії",
            ),
        ),
    ]
