# Generated by Django 6.0 on 2026-01-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_researcher_bio_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Назва об'єкта"),
                ),
                ("description", models.TextField(verbose_name="Опис")),
                ("position_x", models.FloatField(verbose_name="Координата X")),
                ("position_y", models.FloatField(verbose_name="Координата Y")),
                ("position_z", models.FloatField(verbose_name="Координата Z")),
                (
                    "castle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="main.castle",
                        verbose_name="Замок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка інтересу (POI)",
                "verbose_name_plural": "Точки інтересу",
            },
        ),
    ]
